/**
 * GIS-UIT Building E Digital Twin - Page 01 Logical Floor Grid Fixture
 * Fixture ID: page01-floor-grid-demo-v1
 *
 * CRITICAL INVARIANTS:
 * - Pure logical 2D grid matrix (NOT 3D/BIM geometry or physical coordinates)
 * - Stable, unique cellIds across fixture versions
 * - Connects to Page 03 CO2 demo rooms where mapping exists; unmapped rooms remain honest
 * - Corridor and service cells never receive fabricated sensor values
 */

import { FloorConfig } from '@/types/dashboard-overview';

export const OVERVIEW_GRID_FIXTURE_ID = 'page01-floor-grid-demo-v1';
export const OVERVIEW_GRID_VERSION = '1.0.0';

export const BUILDING_E_FLOOR_CONFIGS: FloorConfig[] = [
  {
    floorId: 'T6',
    label: 'Tầng 6',
    shortLabel: 'T6',
    levelNumber: 6,
    rows: 3,
    columns: 5,
    roomCount: 8,
    cells: [
      // Row 0: North wing rooms + service
      {
        cellId: 'CELL-E6-01',
        floorId: 'T6',
        row: 0,
        column: 0,
        label: 'Phòng E6.1',
        kind: 'room',
        roomDemoId: 'DEMO-E-601',
        description: 'Phòng E6.1',
      },
      {
        cellId: 'CELL-E6-02',
        floorId: 'T6',
        row: 0,
        column: 1,
        label: 'Phòng E6.2',
        kind: 'room',
        roomDemoId: 'DEMO-E-602',
        description: 'Phòng E6.2',
      },
      {
        cellId: 'CELL-E6-03',
        floorId: 'T6',
        row: 0,
        column: 2,
        label: 'Phòng E6.3',
        kind: 'room',
        roomDemoId: 'DEMO-E-403',
        description: 'Phòng E6.3',
      },
      {
        cellId: 'CELL-E6-04',
        floorId: 'T6',
        row: 0,
        column: 3,
        label: 'Phòng E6.4',
        kind: 'room',
        roomDemoId: 'DEMO-E-402',
        description: 'Phòng E6.4',
      },
      {
        cellId: 'CELL-E6-SVC1',
        floorId: 'T6',
        row: 0,
        column: 4,
        label: 'KT Điện E6',
        kind: 'service',
        roomDemoId: null,
        description: 'KT Điện E6',
      },
      // Row 1: Corridor spine + lobby + stair
      // {
      //   cellId: 'CELL-E6-CORR1',
      //   floorId: 'T6',
      //   row: 1,
      //   column: 0,
      //   label: 'Hành lang Tây',
      //   kind: 'corridor',
      //   roomDemoId: null,
      // },
      {
        cellId: 'CELL-E6-CORR2',
        floorId: 'T6',
        row: 1,
        column: 1,
        label: 'Hành lang Giữa',
        kind: 'corridor',
        roomDemoId: null,
      },
      {
        cellId: 'CELL-E6-LOBBY',
        floorId: 'T6',
        row: 1,
        column: 2,
        label: 'Sảnh Tầng 6',
        kind: 'room',
        roomDemoId: 'DEMO-E-103',
        description: 'Khu vực sảnh chung Tầng 6',
      },
      // {
      //   cellId: 'CELL-E6-CORR3',
      //   floorId: 'T6',
      //   row: 1,
      //   column: 3,
      //   label: 'Hành lang Đông',
      //   kind: 'corridor',
      //   roomDemoId: null,
      // },
      {
        cellId: 'CELL-E6-STAIR',
        floorId: 'T6',
        row: 1,
        column: 4,
        label: 'Thang bộ T6',
        kind: 'service',
        roomDemoId: null,
      },
      // Row 2: South wing rooms + service
      {
        cellId: 'CELL-E6-05',
        floorId: 'T6',
        row: 2,
        column: 0,
        label: 'Phòng E6.5',
        kind: 'room',
        roomDemoId: 'DEMO-E-401',
        description: 'Phòng E6.5',
      },
      {
        cellId: 'CELL-E6-06',
        floorId: 'T6',
        row: 2,
        column: 1,
        label: 'Phòng E6.6',
        kind: 'room',
        roomDemoId: 'DEMO-E-202',
        description: 'Phòng E6.6',
      },
      {
        cellId: 'CELL-E6-07',
        floorId: 'T6',
        row: 2,
        column: 2,
        label: 'Phòng E6.7',
        kind: 'room',
        roomDemoId: 'DEMO-E-201',
        description: 'Phòng E6.7',
      },
      // {
      //   cellId: 'CELL-E6-LAB',
      //   floorId: 'T6',
      //   row: 2,
      //   column: 3,
      //   label: 'Lab IoT E6',
      //   kind: 'room',
      //   roomDemoId: null, // intentionally unmapped to test empty state
      //   description: 'Phòng thực nghiệm IoT (chưa gắn cảm biến)',
      // },
      // {
      //   cellId: 'CELL-E6-SVC2',
      //   floorId: 'T6',
      //   row: 2,
      //   column: 4,
      //   label: 'KT Nước E6',
      //   kind: 'service',
      //   roomDemoId: null,
      //   description: 'Hộp gen kỹ thuật cấp thoát nước',
      // },
    ],
  },
  {
    floorId: 'T4',
    label: 'Tầng 4',
    shortLabel: 'T4',
    levelNumber: 4,
    rows: 2,
    columns: 4,
    roomCount: 4,
    cells: [
      {
        cellId: 'CELL-E4-01',
        floorId: 'T4',
        row: 0,
        column: 0,
        label: 'Phòng E4.1',
        kind: 'room',
        roomDemoId: 'DEMO-E-101',
        description: 'Phòng hội thảo khoa học Tầng 4',
      },
      {
        cellId: 'CELL-E4-02',
        floorId: 'T4',
        row: 0,
        column: 1,
        label: 'Phòng E4.8',
        kind: 'room',
        roomDemoId: 'DEMO-E-102',
        description: 'Phòng giảng viên Tầng 4',
      },
      {
        cellId: 'CELL-E4-CORR1',
        floorId: 'T4',
        row: 0,
        column: 2,
        label: 'Hành lang T4',
        kind: 'corridor',
        roomDemoId: null,
      },
      {
        cellId: 'CELL-E4-SVC1',
        floorId: 'T4',
        row: 0,
        column: 3,
        label: 'Kỹ thuật T4',
        kind: 'service',
        roomDemoId: null,
      },
      {
        cellId: 'CELL-E4-MEET',
        floorId: 'T4',
        row: 1,
        column: 0,
        label: 'Phòng họp E4',
        kind: 'room',
        roomDemoId: null,
        description: 'Phòng họp bộ môn (chưa có cảm biến)',
      },
      {
        cellId: 'CELL-E4-LAB',
        floorId: 'T4',
        row: 1,
        column: 1,
        label: 'Lab Mạng E4',
        kind: 'room',
        roomDemoId: null,
        description: 'Phòng lab hệ thống mạng',
      },
      {
        cellId: 'CELL-E4-CORR2',
        floorId: 'T4',
        row: 1,
        column: 2,
        label: 'Sảnh thang T4',
        kind: 'corridor',
        roomDemoId: null,
      },
      {
        cellId: 'CELL-E4-STORAGE',
        floorId: 'T4',
        row: 1,
        column: 3,
        label: 'Kho thiết bị',
        kind: 'service',
        roomDemoId: null,
      },
    ],
  },
  {
    floorId: 'T2',
    label: 'Tầng 2',
    shortLabel: 'T2',
    levelNumber: 2,
    rows: 2,
    columns: 3,
    roomCount: 3,
    cells: [
      {
        cellId: 'CELL-E2-01',
        floorId: 'T2',
        row: 0,
        column: 0,
        label: 'Phòng E2.1',
        kind: 'room',
        roomDemoId: null,
        description: 'Phòng học lý thuyết Tầng 2',
      },
      {
        cellId: 'CELL-E2-02',
        floorId: 'T2',
        row: 0,
        column: 1,
        label: 'Phòng E2.2',
        kind: 'room',
        roomDemoId: null,
        description: 'Phòng thực hành máy tính',
      },
      {
        cellId: 'CELL-E2-SVC',
        floorId: 'T2',
        row: 0,
        column: 2,
        label: 'Kỹ thuật T2',
        kind: 'service',
        roomDemoId: null,
      },
      {
        cellId: 'CELL-E2-CORR',
        floorId: 'T2',
        row: 1,
        column: 0,
        label: 'Hành lang T2',
        kind: 'corridor',
        roomDemoId: null,
      },
      {
        cellId: 'CELL-E2-03',
        floorId: 'T2',
        row: 1,
        column: 1,
        label: 'Phòng E2.3',
        kind: 'room',
        roomDemoId: null,
        description: 'Phòng văn thư khoa',
      },
      {
        cellId: 'CELL-E2-STAIR',
        floorId: 'T2',
        row: 1,
        column: 2,
        label: 'Thang bộ T2',
        kind: 'service',
        roomDemoId: null,
      },
    ],
  },
  {
    floorId: 'T1',
    label: 'Tầng 1',
    shortLabel: 'T1',
    levelNumber: 1,
    rows: 2,
    columns: 3,
    roomCount: 3,
    cells: [
      {
        cellId: 'CELL-E1-LOBBY',
        floorId: 'T1',
        row: 0,
        column: 0,
        label: 'Sảnh chính E',
        kind: 'room',
        roomDemoId: null,
        description: 'Sảnh đón tiếp và kiểm soát vào ra',
      },
      {
        cellId: 'CELL-E1-ADMIN',
        floorId: 'T1',
        row: 0,
        column: 1,
        label: 'Văn phòng E1',
        kind: 'room',
        roomDemoId: null,
        description: 'Văn phòng hành chính tòa nhà E',
      },
      {
        cellId: 'CELL-E1-SVC',
        floorId: 'T1',
        row: 0,
        column: 2,
        label: 'KT Trung tâm',
        kind: 'service',
        roomDemoId: null,
        description: 'Phòng tủ điện và điều khiển trung tâm',
      },
      {
        cellId: 'CELL-E1-HALL',
        floorId: 'T1',
        row: 1,
        column: 0,
        label: 'Hội trường E',
        kind: 'room',
        roomDemoId: null,
        description: 'Hội trường lớn Tầng 1',
      },
      {
        cellId: 'CELL-E1-CORR',
        floorId: 'T1',
        row: 1,
        column: 1,
        label: 'Hành lang T1',
        kind: 'corridor',
        roomDemoId: null,
      },
      {
        cellId: 'CELL-E1-STAIR',
        floorId: 'T1',
        row: 1,
        column: 2,
        label: 'Thang máy & bộ',
        kind: 'service',
        roomDemoId: null,
      },
    ],
  },
];

export function getFloorConfigById(floorId: string): FloorConfig | undefined {
  return BUILDING_E_FLOOR_CONFIGS.find((f) => f.floorId === floorId);
}
